blank_issues_enabled: false
contact_links:
  - name: Questions & ideas
    url: https://github.com/Vrin-cloud/supersede/discussions
    about: For open-ended questions and discussion, use Discussions.
